# Generated by Django 2.1.7 on 2019-03-27 16:42

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaskTask',
            fields=[
                ('task_key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32, null=True)),
                ('result', picklefield.fields.PickledObjectField(editable=False, null=True)),
            ],
        ),
    ]
